language: node_js

node_js:
    - "10"
    - "12"

sudo: false

env:
    - HAPI_VERSION="17"

install:
    - npm install -g json
    - json -I -f package.json -e "this.devDependencies.hapi=\"$HAPI_VERSION\""
    - npm install
